### ISSUE TITLE
When cloning repo and not signed in, ask the user to sign in

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#1716]
Testing https://github.com/microsoft/vscode/issues/96280

![image](https://user-images.githubusercontent.com/35271042/80563865-2911e500-89a1-11ea-8d3e-c8b22b75819e.png)

Attempted to clone a repo without being logged in and was hit with this weird error. There is no clear action as to what the user should do. I expected to be asked to sign in and for this error to be friendlier as I assume this means I am not signed in.

**Comment by joaomoreno** [comment]
This is a dupe which was fixed in today's GHPR nightly. Can you try again @misolori?

**Comment by misolori** [comment]
Tried this today and it's still happening. It's unclear from #1700 what is the expected behavior, I expect to be asked to sign in if I am already not.

**GitHub PR Extension**
Version: 2020.4.39782

**Insiders**
Version: 1.45.0-insider
Commit: 4bd206856db30c27d38aa0f1fbe74bac6156edc7
Date: 2020-04-29T05:31:36.229Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.5.0

**Comment by joaomoreno** [comment]
@RMacfarlane I thought https://github.com/microsoft/vscode-pull-request-github/pull/1709 fixed this?

**Comment by joaomoreno** [comment]
@misolori I really can't repro this. Are you sure you are on latest Insiders and latest GHPR nightly?

https://msit.microsoftstream.com/video/6400a4ff-0400-96d0-a721-f1ea8ac5c139?list=studio

**Comment by RMacfarlane** [comment]
I'm also not able to repro this now, @misolori can you try again when you have a chance?

**Comment by misolori** [comment]
Just tried this again and it's fixed, there's a notification to sign in. Thanks for following up!
