### ISSUE TITLE
GraphQL error when editing comment on PR

### ISSUE THREAD

**Issue by thezanke** [microsoft/vscode-pull-request-github#1922]
Issue Type: <b>Bug</b>

1. Check out a PR for review
2. Add a comment to the main discussion thread
3. Edit comment & Save

Expected Results: The comment is edited and saved
Actual Results: The comment looks like it saved but I get a toast in VSCode with the following error:
> GraphQL error: Could not resolve to PullRequestReviewComment node with the global id of 'xxxxxxxxxxxxxxxxxxxxxx=='.

The comment textarea leaves edit mode and looks like it saved but if I refresh the PR screen the comment re-enters edit mode.

Extension version: 0.17.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Chuxel** [comment]
@RMacfarlane FYI - I'm also seeing this in GitHub Codespaces right now.  I tried to add a line comment and start a review and got the following notifications:

![image](https://user-images.githubusercontent.com/312252/92179421-7e4f7e80-edf9-11ea-8bbe-fc3c9fbc202c.png)

Logs showed
```
[Info] /home/vscode/.ssh/config: ENOENT: no such file or directory, open '/home/vscode/.ssh/config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] Found GitHub remote
[Info] Review> current branch pr/bamurtaugh/3966 is associated with pull request #3966
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
```
Chrome Dev Tools had a bit more to say:
```
notificationsAlerts.ts:40 Starting review failed: Error: GraphQL error: Resource not accessible by integration
onDidChangeNotification @ notificationsAlerts.ts:40
console.ts:137 [Extension Host] No editors associated with document: commentinput-1-1599171608571.md
t.log @ console.ts:137
notificationsAlerts.ts:40 Creating comment failed: Error: Cannot reply to temporary comment
onDidChangeNotification @ notificationsAlerts.ts:40
console.ts:137 [Extension Host] No editors associated with document: commentinput-2-1599171610033.md
t.log @ console.ts:137
chuxel-bamurtaugh-vscode-docs-r92w.github.dev/:1 Failed to load resource: the server responded with a status of 504 (Gateway Timeout (dev tools: https://bugs.chromium.org/p/chromium/issues/detail?id=823392))
```

Is this due to the access token scope?

**Comment by RMacfarlane** [comment]
@Chuxel Is this in a private repo? I think this is likely https://github.com/microsoft/vscode-internalbacklog/issues/1069

**Comment by Chuxel** [comment]
It's in vscode-docs, so public. I think this is web specific - didn't repro in vscode locally.  Could be related to https://github.com/github/codespaces/issues/1093 or not... that seemed to be related to snippets, but could point to networking.

**Comment by thoward27** [comment]
I'm seeing the same behavior locally with a private repo

**Comment by therealchjones** [comment]
I've got the same, local with public repo

**Comment by Falpangaea** [comment]
I'm also experiencing the same behavior locally with a private repo - comments are showing up in VSC pretty consistently (sometimes they take awhile to sync) and I can react to a comment locally with success, but I can't respond or Resolve Conversation.

**Comment by mike-loux-planview** [comment]
Getting something similar as well with a PR created some time ago, but reviewed yesterday.  When I try to Resolve Conversation, I get the following error:
![image](https://user-images.githubusercontent.com/62146387/132861822-ef87c972-9618-4626-95d9-0678435ecca2.png)
Repo is private, extension version is 0.29.2.

**Comment by Parth220** [comment]
![image](https://user-images.githubusercontent.com/34073886/134431581-3cd4d07b-78bd-41a7-be88-301be89045d8.png)
Same issue, resolving a PR review comment in a private repo.

**Comment by alexr00** [comment]
Closing as the lack of reports in the last year indicates that this was likely fixed in the mean time.

**Comment by niemeyer** [comment]
Maybe people just assumed they didn't need to report again? I'm still seeing the same error while trying to edit a PR:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/378683/d050eb47-3334-443d-87be-6768f07517b4)

This happens both with the release and pre-release versions.

**Comment by niemeyer** [comment]
Sorry, maybe this is a different issue. A commenter reported this error, but the original report is different. I'm going to open a separate issue for this.

**Comment by alexr00** [comment]
Got some great repo steps in https://github.com/microsoft/vscode-pull-request-github/issues/5325, closing a duplicate
