### ISSUE TITLE
Fetching pull requests for remote 'origin' failed,

### ISSUE THREAD

**Issue by alexandremsouza1** [microsoft/vscode-pull-request-github#1941]
Fetching pull requests for remote 'origin' failed, please check if the url https://github.com/****/*****.git is valid.

- Extension version: v0.17.0
- VSCode Version:
Versão: Commit de 1.46.1 (system setup): cd9ea6488829f560dc949a8b2fb789f3cdc05f5d Data: 2020-06-17T21:13:20.174Z elétron: 7.3.1 Chrome: 78.0.3904.130 node. js: 12.8.1 V8: 7.8.279.23-electron.0 OS: Windows_NT x64 10.0.18363
- OS: Windows 10 

![image](https://user-images.githubusercontent.com/38253342/86017487-74289280-b9fa-11ea-9204-2cbc4313fe30.png)

**Important note.

This specific repository is private and recently ceased to be a user to become an organization**

**Comment by RMacfarlane** [comment]
@alexandremsouza1 Can you run the command `Developer: Toggle Developer Tools` and see if there is any additional error info in the console? Do you see the failed request in the network tab there?

**Comment by alexandremsouza1** [comment]
> @alexandremsouza1 Can you run the command `Developer: Toggle Developer Tools` and see if there is any additional error info in the console? Do you see the failed request in the network tab there?

![image](https://user-images.githubusercontent.com/38253342/86032974-95937980-ba0e-11ea-9e46-2a1db73e2813.png)

**Comment by RMacfarlane** [comment]
The error about the buffer can be ignored, what's the warning above it?

This notification is shown when the fetch call 404's, can you double check that the you're able to access `https://github.com/***/***` normally in the browser, and that the user you're currently logged into VSCode with has access ot this repo?

**Comment by alexandremsouza1** [comment]
> O erro sobre o buffer pode ser ignorado, qual é o aviso acima?
> 
> Essa notificação é mostrada quando a chamada de busca 404 é, você pode verificar `https://github.com/***/***`novamente se consegue acessar normalmente no navegador e se o usuário com o qual está conectado no VSCode atualmente tem acesso a este repo?


Yes, I have access to the repository.

if I click on "sigin out and sigin in" it works.

The problem is having to do this every time.

**Comment by alexandremsouza1** [comment]
![image](https://user-images.githubusercontent.com/38253342/86129792-a220dc00-bab9-11ea-8f51-17197118f672.png)

**Comment by alexandremsouza1** [comment]
![image](https://user-images.githubusercontent.com/38253342/86135085-bd431a00-bac0-11ea-9bff-373e3dd36471.png)
 
Every time i click on the item i lose my credentials

**Comment by alexandremsouza1** [comment]
It actually looks like I'm losing my token when the plugin to refresh

**Comment by alexandremsouza1** [comment]
![image](https://user-images.githubusercontent.com/38253342/96033692-cde08b80-0e36-11eb-8691-e6e83d4134da.png)
it's still happening

![image](https://user-images.githubusercontent.com/38253342/96033725-d9cc4d80-0e36-11eb-8ff4-622cdc4f25d8.png)

**Comment by alexandremsouza1** [comment]
https://drive.google.com/file/d/1nMUjmox89IoG4CcKNVggBKXX4v4DIoYc/view?usp=sharing

**Comment by alexandremsouza1** [comment]
![Uploading image.png…]()

**Comment by alexandremsouza1** [comment]
![image](https://user-images.githubusercontent.com/38253342/96039011-63334e00-0e3e-11eb-92a6-642add2bc01b.png)

**Comment by RMacfarlane** [comment]
@alexandremsouza1 Can you also share if there is anything in the Output panel when "GitHub Pull Request" is selected? And is there anything in the console if you run the command "Developer: Toggle Developer Tools"?

**Comment by alexandremsouza1** [comment]
anything

https://drive.google.com/file/d/1uyNl3KFtsRmwNWfOfnvdZJVEwSeb8bVw/view?usp=sharing

**Comment by alexandremsouza1** [comment]
![image](https://user-images.githubusercontent.com/38253342/96120165-7ab51a00-0ec4-11eb-844f-c068cf5ee332.png)

**Comment by douglascayers** [comment]
I'm also getting this error recently although via git CLI and browser I'm able to access the repositories just fine.

![image](https://user-images.githubusercontent.com/4142577/98572593-6b36b000-227b-11eb-8a0a-d0d2257ee5f6.png)

### Extension Version
v0.21.0

![image](https://user-images.githubusercontent.com/4142577/98572902-c8326600-227b-11eb-8847-4f27d810fed4.png)


### About Visual Studio Code
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:14:40.758Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

### Things I've Tried
I even tried setting my personal access token to our GitHub Enterprise instance in settings according to [this article](https://medium.com/@brianhague/viewing-github-pull-requests-in-vscode-with-github-enterprise-859a07e6d353).

```json
    "githubPullRequests.hosts": [
        {
            "host": "https://our-github-enterprise.com",
            "token": "my-access-token",
            "username": "my-user-name"
        }
    ],
```

**Comment by douglascayers** [comment]
Update: I resolved the issue on my Mac by getting Visual Studio Code to reprompt me for my git credentials when fetching from the remote repository.

Your mileage may vary, this is what I did:
1. Close Visual Studio Code
2. Open Keychain Access app
3. Search for "git" and delete the "internet password" entry for the GitHub domain you're having issues with
![image](https://user-images.githubusercontent.com/4142577/98574827-06c92000-227e-11eb-802b-9526f74a28fa.png)

4. Open Visual Studio Code then open an integrated terminal to your local git repository
5. In the terminal, run `git fetch`
6. When prompted, enter your git credential username
![image](https://user-images.githubusercontent.com/4142577/98574701-dda88f80-227d-11eb-998c-ee689cf05701.png)

7. When prompted, enter your git credential password or access token
![image](https://user-images.githubusercontent.com/4142577/98574893-1b0d1d00-227e-11eb-9232-5196a1443196.png)

8. Reload Visual Studio Code to confirm no more extension error about unable to reach the repository url

**Comment by douglascayers** [comment]
Possible related to #795

**Comment by RMacfarlane** [comment]
@alexandremsouza1 Do you still see this issue with the latest version of VS Code?

**Comment by hugo-licon** [comment]
I'm having the same issue. I have two accounts in my computer. 
The way I set them up was using SSH with a config file:
```
Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa

Host github-work
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_work_rsa
```
and when I need to clone a repository I do the following: 
`git clone git@github-work:****-org/****.git` This is for my work account
`git clone git@github.com:HugoLiconV/****git` This is for my personal account
This works fine but when I tried to set up the extension to work for my work account I get the same error.
What I did was to add this configuration: 
```
  "githubPullRequests.hosts": [

    {
      "host": "https://github-work.com",
      "token": "5abddc5f2f**********************" // The token I got it from `Personal access tokens` 
    }
  ]
```

**Comment by alexr00** [comment]
There is now community provided support for enterprise. If you're still seeing an issue please open a new issue!

**Comment by ImaduddinKhan** [comment]
I think if you who are facing the problem are using GitLab (i mean if the repositories are in there) and in VS code you are signed in with both Microsoft and GitHub accounts then sign out from GitHub and then restart and try again.

**Comment by adampuchejda** [comment]
Hi, 
I’m having the same issue (error message: “Fetching pull requests for remote 'origin' failed, please check if the url [https://github.com/***/***.git] is valid”). I’m using VSCode 1.60 on macOS 11.4 with the extension version 0.30. Below I post console messages I get associated with this extension. I'm not using Github Enterprise and this is a private repo.

![Zrzut ekranu 2021-09-8 o 19 29 08](https://user-images.githubusercontent.com/85750522/132556706-52fcd7e0-622a-47a9-8cb3-5842bf1045ab.png)

![Zrzut ekranu 2021-09-8 o 19 29 27](https://user-images.githubusercontent.com/85750522/132556734-1cce4386-e33f-44b1-883c-a7356ab6d626.png)

Thanks for looking into this.

Best,
Adam

**Comment by roisafirorichard** [comment]
I'm having the same issue, it has something to do with #3099 , the extension considers `git@github-personal.com:xxxx/xxxxx` not a valid url. please have a look at this.

**Comment by kenobi-io** [comment]
I'm having the same issue

**Comment by juhovuori** [comment]
Also suffering from the same issue.

**Comment by skorpions2000** [comment]
Also suffering from the same issue. Problem EXIST!

**Comment by sakrlog** [comment]
@skorpions2000 you closed this issue and you mentioned another closed and also not solved :/

**Comment by McLovin77** [comment]
Hey so for me the issue was that I was connected to my VSCode with 2 gh accounts (personal and work), and I signed out of the personal one and the extension all of a sudden started working (after months of just having it there and never using it cuz it never worked), I suggest you disconnect and reconnect to your accounts, play with it a little until it works, doesn't feel like they're gonna solve it

![image](https://user-images.githubusercontent.com/86220757/177729621-c00a780e-604e-4d47-bcdd-97e1de0f5b64.png)

**Comment by alexr00** [comment]
@McLovin77 thank you for posting your solution. That the extension doesn't tell you that there are 2 accounts and it doesn't work with 2 accounts is a bug. We can do better and tell you that you should sign out of one account: https://github.com/microsoft/vscode-pull-request-github/issues/3693

**Comment by alexr00** [comment]
Folks in this thread: I am working on improving the GitHub Enterprise support. If you are willing to help me find and tackle the issues you're seeing please do the following:
1. Install the pre-release version of the extension
2. When you see a bug, open a new issue with the following details:
  a. GitHub Enterprise version number
  b. Repro steps
  c. Output from GitHub Pull Request
  d. Any errors you see in the developer tools

**Comment by joechea-aupp** [comment]
I experienced the same problem, spent 1h and realized that I had more than one github account sign-in on vscode. log out the rest and keep only one account sign in, solved for me.

**Comment by ChicoMetal** [comment]
I faced the same issue, I logged out from one account and then it worked.

**Comment by vvoldi** [comment]
fixed in the latest versions of VS code, they added multiple account support

**Solution:** 

1. right-click on the extension 
2. click Account Preferences
3. select the necessary account (or add a new one here)
4. restart vs code

![Image](https://github.com/user-attachments/assets/0dc7d9ef-0b1a-403a-b1e6-6309bd137e5c)

**Comment by fenil555** [comment]
I still have this issue with the given error.

![Image](https://github.com/user-attachments/assets/1957dfb4-d4d1-45be-ac7e-d266450d8015)

**Comment by madbolyNoon** [comment]
I was able to replicate the same issue as @fenil555.
Resolved it by first selecting `GitHub: Sign out`, and then using `GitHub Pull Requests: Sign in` to log back in.
