### ISSUE TITLE
Dropdowns missing all entries after push to brach

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2415]
microsoft/vscode#114967

2. New branch.
1. Create a commits, don't push
2. Try to create a PR, get message about needing to push
3. Press "Cancel" (I used the left cancel, https://github.com/microsoft/vscode-pull-request-github/issues/2413)
4. Focus the explorer view, then back to pr view
5. Dropdowns empty:

![recording (7)](https://user-images.githubusercontent.com/8586769/105917893-e3de1a80-5fe7-11eb-8504-8c20d826e2f9.gif)

**Comment by RMacfarlane** [comment]
I'm not able to repro this so believe I have fixed it as part of other changes. Now when clicking cancel a message should appear on the view

**Comment by JacksonKearl** [comment]
I can still reproduce in latest insiders (v2021.1.39421):
The native dialogue asking to push the changes doesn't appear in this screenshot but I hit cancel on it.
![recording (9)](https://user-images.githubusercontent.com/8586769/106212758-1d498e00-6180-11eb-834f-f85616a26fb7.gif)

**Comment by RMacfarlane** [comment]
Thanks, got it this time 😄
