### ISSUE TITLE
Fetching pull requests for remote 'origin' failed, please check if the url

### ISSUE THREAD

**Issue by Nagesh89V** [microsoft/vscode-pull-request-github#2811]
Issue Type: <b>Bug</b>

After committing every new change in the source control i get a popup "Fetching pull requests for remote 'origin' failed, please check if the url is valid".
Source: GitHub Pull Requests and Issues (Extension)
Please assist

Extension version: 0.27.1
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.33GB (7.55GB free)|
|Process Argv|--crash-reporter-id 8e29ad33-d777-4bd4-b3fb-f76a1be9d2b3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30329803
vscextlangct:30322307
binariesv615:30325510
vsccppwt:30329788
aatestflightcf:30331712

```

</details>

**Comment by alexr00** [comment]
This should be fixed in the nighty build of this extension.

**Comment by Nagesh89V** [comment]
It’s still not working.
Getting the same error.

Vennlig hilsen / Kind Regards,

Nagesh V
DC Ops Wintel  - Avarn Security
Mobile : +91 9964380087 | Desk number : +91 80 30670263

**Comment by jplatte** [comment]
I'm seeing the same error, might be relevant that I use ssh URLs. I'm using plugin version v0.29.2.

Please reopen @alexr00.
