### ISSUE TITLE
Checked out button misaligned

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-pull-request-github#4289]
Version: 1.74.0-insider
Commit: 493a541735b84de36b628750ba716a430669cb7f
Date: 2022-12-02T05:25:16.689Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: Yes

Steps to Reproduce:

1. Create a new pull request
2. Open the pull request to see the details

<img width="798" alt="image" src="https://user-images.githubusercontent.com/3372902/205619933-76ed90b4-3e6b-41b7-86e5-86b588462e6d.png">

**Comment by alexr00** [comment]
Looks like this has been fixed in the mean time.

**Comment by lszomoru** [comment]
Still seeing it:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/3372902/214575887-50ce4cad-0f15-4b1c-bdae-fb6eef984046.png">
