### ISSUE TITLE
When using workspace with two repos, commenting is only available in the first repo

### ISSUE THREAD

**Issue by johnknoop** [microsoft/vscode-pull-request-github#5409]
- Extension version:
v0.74.1
- VSCode Version:
1.83.1 (system setup)
- OS:
Win11 (Windows_NT x64 10.0.22621)
- Repository Clone Configuration (single repository/fork of an upstream repository):
Single
- Github Product (Github.com/Github Enterprise version x.x.x):
Enterprise

Steps to Reproduce:

1. Open the root folder of a repo in VS Code.
2. Add another folder to the workspace.
3. Open the Pull Requests view
4. Click on a file from the pull request file tree of the first repo you opened in VS Code
5. Notice how you can add comments. Both in diff view and file view:
6. Now click on a file from the pull request file tree of the SECOND repo you opened
7. Notice how the grey line isn't there anymore, neither in diff view of in file view:

The extension seems to only add the commenting capability to the _first_ folder in your workspace, because if I open the workspace settings (JSON) and flip the order of the elements in the `folders` array, then I can suddenly start making comments in the other folder, but no longer in the one I opened initially.

**Comment by alexr00** [comment]
This should be fixed in version 0.76.

**Comment by johnknoop** [comment]
I'm on 0.76.0 and I still have the issue:

![b9ab7802-8a97-4700-9b3b-3925fd447611](https://github.com/microsoft/vscode-pull-request-github/assets/3394270/5927584e-a555-401b-b5f6-7620527be28a)

In fact another regression seems to have appeared: now the Comments area in the right panel only lists comments for one of the three opened repos in my workspace, and that repo isn't even the first one in the `workspace.json` folders array, but the second.

**Comment by alexr00** [comment]
@johnknoop is this for PRs you have checked out, or PRs that you're browsing from the "Pull Requests" view but haven't checked out? Your most recent gif is the former, but I want to double check that this has always been your scenario.

**Comment by johnknoop** [comment]
@alexr00 it's PR's I have checked out, that I'm working on myself.

**Comment by johnknoop** [comment]
Also, please tell me when I can remove the screengrabs from this page, since they contain code from our private repos. :)

**Comment by alexr00** [comment]
@johnknoop I removed them now, though I don't see a way to remove them from the history of your original post (I could remove  them from the history of your comment).

**Comment by alexr00** [comment]
I see a way that this could happen. You have 2 PRs checked out, and they're in different repos. Did they happen to have the same PR number?

**Comment by johnknoop** [comment]
No they had different PR numbers.

I just tried to reproduce this issue again with two new PRs, but this time all the comments show up fine. So I think we can close this.

Thanks a ton for your assistance!
