### ISSUE TITLE
`Failed to execute git` thrown when attempting to view PR Description in "GitHub" tab

### ISSUE THREAD

**Issue by jheinem1** [microsoft/vscode-pull-request-github#5744]
`Failed to execute git` is thrown when clicking on the "Description" button under pull requests.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/70541819/a0916a02-6101-4867-8e5e-911140681b24)

![image](https://github.com/microsoft/vscode-pull-request-github/assets/70541819/9e3b512a-014c-4532-b662-dae6af8d872d)

There doesn't appear to be any errors thrown in the extension's output, but it occurs when clicking on the "Description" button under the pull request. Opening the pull request under the "GitHub Pull Request" tab instead of the "GitHub" tab does fetch the information correctly.

I found #5668 and #5743 to be somewhat similar to this issue, however that error seems to occur in "write" operations, whereas this fails to fetch information from GitHub.

- Extension version: v0.80.0
- VSCode Version: 1.86.0 (tested and still not working in 1.86.1)
- OS: Nobara Linux 39 (KDE Plasma) x86_64
- Repository Clone Configuration (single repository/fork of an upstream repository): single repository
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Click on the "Description" button under a pull request under the "GitHub" tab on the left.

**Comment by jheinem1** [comment]
It seems that this only occurs when I'm not fully signed in- I was prompted in the pull request screen to "Sign In for Additional Permissions", which seemed to resolve the issue.
I wasn't prompted to sign in through the account icon or when attempting to access the PR description from the GitHub tab though.

**Comment by ramunas-k** [comment]
What helped me was executing `git fetch` before opening the description. I do not have actual logs at hand but `git` is not happy about not having local branch PR is created from

**Comment by alexr00** [comment]
Next time someone sees this, can you please share the output from the Output view for "git"?

**Comment by makeitraina** [comment]
> Next time someone sees this, can you please share the output from the Output view for "git"?

Same thing happens for me. Here is the output from both github pull request and git
github pull request
![Screenshot 2024-03-07 at 11 17 09 AM](https://github.com/microsoft/vscode-pull-request-github/assets/14355367/befc790f-507a-407e-a0f7-b3efd1093b24)
```
2024-03-07 11:16:59.153 [info] FolderRepositoryManager+0> Found GitHub repo for pr #711: yes
2024-03-07 11:16:59.850 [info] FolderRepositoryManager+0> Found GitHub pr repo for pr #711: yes
2024-03-07 11:16:59.850 [info] GitHubRepository> Fetch branch release - enter
2024-03-07 11:17:00.049 [info] GitHubRepository> Fetch branch release - done: true
```

git
![Screenshot 2024-03-07 at 11 17 53 AM](https://github.com/microsoft/vscode-pull-request-github/assets/14355367/679bf52f-66a5-4454-b286-4361b831ba08)
```
2024-03-07 11:16:56.963 [info] > git check-ignore -v -z --stdin [26ms]
2024-03-07 11:16:59.273 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z origin/krupalinakrani/web-675-implement-new-navbar-and-dropdowns..origin/release [122ms]
2024-03-07 11:16:59.273 [info] fatal: ambiguous argument 'origin/krupalinakrani/web-675-implement-new-navbar-and-dropdowns..origin/release': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
2024-03-07 11:16:59.273 [info] > git config --local -l [124ms]
```

**Comment by ramunas-k** [comment]
@alexr00 I can confirm that these are the same outputs form "Git" and "Github Pull Requests" after clicking on PR description.

@makeitraina thanks for posting

**Comment by ramunas-k** [comment]
@alexr00 
Today my extension got updated to `v0.82.0`. For me the issue still persists with the same symptoms observed in Git output
```
[info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z origin/branch1..origin/develop [65ms]
[info] fatal: ambiguous argument 'origin/branch1..origin/develop': unknown revision or path not in the working tree.
[info] > git config --local -l [77ms]
[info] > git config --local branch.branch1 [1ms]
[warning] git config failed: Failed to execute git
```
(real branch name is changed to `branch1` in logs above)

VSCode is configured *not* to sync repository automatically. Could this be an issue?
```
// settings.json
"git.autofetch": false,
```
When I do `git fetch` in terminal everything works fine then

If your PR did not make it to newest extension version just ignore my post

Thanks

**Comment by GeigerJ2** [comment]
Just putting this out there in case someone ends up in a similar situation, and it could be helpful: I had the same issue, but running plain `git fetch` did not resolve it as the `git log` command that was run by the extension was actually referencing `upstream/main`, i.e.:
`git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z <remote_pr_branch>..upstream/main`

However, in my `.git/config`, the remote "origin" was pointing to my own fork, and not the "upstream" repo that the PR was actually created on, while remote "upstream" was actually not defined. So yeah, a bit of a messed up setup, but long story short, running `git fetch upstream` solved the problem.

**Comment by alexr00** [comment]
To verify:
- Make sure you don't have the git extension configured to automatically fetch
- Have a GitHub repo clone that has not fetched in a while
- Open that folder in GitHub
- Expand one of the most recent PRs, specifically one who's branch you haven't fetched.
- Verify you don't get the error

**Comment by alexr00** [comment]
Fix is available in version 0.82.1.

**Comment by Shmok9** [comment]
#5863

**Comment by festoney8** [comment]
For those still facing this issue:

The `Failed to execute git` pop-up can also be caused when checkout to the PR branch by DNS failure or other network issues. You’ll see the following log and error in VSCode output. Fix your network and retry

```
2026-06-09 16:02:35.080 [info] > git config --local -l [76ms]
2026-06-09 16:02:35.149 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/pr/username/123 refs/remotes/pr/username/123 [65ms]
2026-06-09 16:02:35.149 [warning] [Git][getBranch] No such branch: pr/username/123
2026-06-09 16:02:35.374 [info] > git fetch username branch:pr/username/123 [221ms]
2026-06-09 16:02:35.374 [info] Connection closed by 198.18.0.10 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
2026-06-09 16:02:35.441 [info] > git config --get commit.template [62ms]
2026-06-09 16:02:35.450 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) --ignore-case refs/heads/dev refs/remotes/dev [67ms]
2026-06-09 16:02:35.523 [info] > git status -z -uall [69ms]
2026-06-09 16:02:35.526 [info] > git for-each-ref --sort -committerdate --format %(refname)%00%(objectname)%00%(*objectname) [69ms]
2026-06-09 16:02:35.598 [info] > git config --local -l [66ms]
2026-06-09 16:02:35.665 [info] > git config --local -l [63ms]
2026-06-09 16:02:35.732 [info] > git config --local -l [62ms]
```
