### ISSUE TITLE
Extension fails retrieve PR description from an enterprise repo and throws failed execute git error on vscode

### ISSUE THREAD

**Issue by hnaganur** [microsoft/vscode-pull-request-github#5746]
Until version 0.78.1 of the extension there was issue viewing the PR description in VSCode for any repos. With 0.80.0 and above it fails to retrieve the information from an enterprise/org repo and throws 'failed execute git' error.  The output log doesn't have information in it to see what went wrong.

output log:
<FolderRepositoryManager+0> Found GitHub repo for pr #35308: yes
2024-02-12 07:11:18.390 [info] FolderRepositoryManager+0> Found GitHub pr repo for pr #35308: yes
2024-02-12 07:11:18.390 [info] GitHubRepository> Fetch branch main - enter
2024-02-12 07:11:18.693 [info] GitHubRepository> Fetch branch main - done: true

- Extension version: 0.80.0 and above
- VSCode Version: 1.86.1
- OS: Windows 64 bit
- Repository Clone Configuration (single repository/fork of an upstream repository): fork of an upstream repo
- Github Product (Github.com/Github Enterprise version x.x.x): git version 2.43.0.windows.1

**Comment by hnaganur** [comment]
same as #5744 

Resolved after signing out and signing back in.

**Comment by hcassar93** [comment]
Signing out and back in doesn't fix it for me.

I've tried that in multiple ways, in addition to reinstalling the extension.

Still `failed to execute git` every time when trying to open the description of a PR.

**Comment by skattabrain** [comment]
I have this issue as well. Possible issue - our organization has an enterprise co-pilot program, I'm logged into VS Code with both my personal and enterprise account.
