### ISSUE TITLE
Adding a comment failed: Comment position cannot be negative.

### ISSUE THREAD

**Issue by kaufmann42** [microsoft/vscode-pull-request-github#605]
[File in question](https://github.com/Microsoft/vscode-pull-request-github/blob/f18c482a0b2bd5eb6f57490ab43b689e44cad055/src/view/reviewManager.ts#L334)

- Extension version: 0.2.1
- VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
- OS version: Darwin x64 17.3.0

![image](https://user-images.githubusercontent.com/11468557/47379950-ef805f80-d6c1-11e8-8120-684552096ce5.png)

Steps to Reproduce:

1. Open a file using the navigator on the side panel
2. Attempt to add a comment to the changed file (on the right window panel)
3. Get the above result.

**Comment by jsn-miller** [comment]
This was happening to me because I was on a branch different from that of the PR. After checking out the PR's branch by clicking on the PR title and selecting "Checkout Pull Request", I could then comment on the diffs.

**Comment by RMacfarlane** [comment]
Closing as I haven't been able to reproduce this in the latest version of the extension and think it has been fixed. Please let me know if you see it again. Thanks!

**Comment by baspetersdotjpeg** [comment]
This still appears to be an issue with the following versions:
Extension version: 0.25.0
VS Code version: 1.55.1
OS: macOS Big Sur 11.2.3

Let me know if I can provide any information to reproduce, it seems pretty arbitrary.
