### ISSUE TITLE
Comments panel always shows even if I try to hide it

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#70]

**Comment by rebornix** [comment]
@Tyriar can you elaborate a bit more on this? I hide the comments panel by right click on panel title bar and unpick Comments, it works as expected.

**Comment by rebornix** [comment]
I see the problem, *Comments* label is removed from the panel title bar but the comments are still there.

**Comment by Tyriar** [comment]
I right clicked to hide the comments panel but it kept showing when opening PRs. I guess I'm after something like this `"debug.internalConsoleOptions": "neverOpen"`.

I found out later that review comments are only visible in the comments panel, so https://github.com/Microsoft/vscode-pull-request-github/issues/71 would needs to be done before I am able to work without the comments panel or I'd be losing information.

**Comment by Tyriar** [comment]
Another example of the comments panel being annoying; I just opened xterm.js, checked out a PR branch, opened the terminal and started typing `npm run watch` but the comments panel took panel focus.

**Comment by Tyriar** [comment]
This is still one of the biggest annoyances for me as it always opens as I'm typing in the terminal. I'd like to disable auto showing outright like I can with the debug console.

**Comment by rebornix** [comment]
Now it only pops up for the first session.

**Comment by RMacfarlane** [comment]
I want to add a setting for the comments panels similar to the debug console. The options for debug console are `neverOpen`, `openOnSessionStart`, `openOnFirstSessionStart`, and `openOnDebugBreak`.

The options I'm thinking of for the comments panel are something like:
- "polite/neverOpen", enable the comments panel but never open it without user action
- open whenever a comments provider is registered and there are actually comments in the panel
- open whenever a comments provider is registered

`neverOpen`, `openOnCommentsPresent`, `openOnCommentProviderRegistered`? or maybe `openOnCommentSessionStart` and `openOnCommentSessionStartThatHasComments`?

I think either the second or third option should be the default.

**Comment by Tyriar** [comment]
Sounds great 😃

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/64941, you can now use `"comments.openPanel": "neverOpen"`

**Comment by Tyriar** [comment]
:tada:🐦

**Comment by Milo123459** [comment]
This is still a bug. I added the setting, and it's still showing. Please, fix this. @rebornix

**Comment by Milo123459** [comment]
*When I say it's still showing, I mean, after you restart, the setting is applied, etc, the panel reopens.

**Comment by pnheinsohn** [comment]
Now is with the following line in `settings.json`

````
"comments.openView": "never"

**Comment by Tiberriver256** [comment]
Is there a new way to do this? I have `comments.openView` set to `never` and I still get this every time I try and open my terminal

![Image](https://github.com/user-attachments/assets/af9b3c00-d14f-468f-888b-239c4415b469)

**Comment by m3c-ode** [comment]
Same for me, I don't recall seeing it like 2 months ago, but it takes unnecessary space for me.

**Comment by joshsixx** [comment]
just click the "Reset Location" .
