### ISSUE TITLE
Intellisense popups up in comment code block when it shouldn't

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#917]
vscode: insiders 2019-02-05T10:03:57.911Z
ext version: 1.31.0
macOS

In a comment:

<img width="530" alt="screen shot 2019-02-05 at 11 43 14 am" src="https://user-images.githubusercontent.com/2193314/52299875-65d86300-293b-11e9-894f-390f8710eb7e.png">

In a markdown file:

<img width="178" alt="screen shot 2019-02-05 at 11 43 41 am" src="https://user-images.githubusercontent.com/2193314/52299877-683abd00-293b-11e9-8b45-11fa6baceeed.png">

I have this in my settings:

```
  "[markdown]": {
    "editor.quickSuggestions": false
  }
```

**Comment by trkoch** [comment]
Globally disabling quick suggestions did not have any effect either. I wonder what syntax is detected for the input? I could not inspect the TM scope because focus is lost when searching and invoking command.

**Comment by szhu** [comment]
Having the same issue, I use [Rewrap] and I'm setting it to auto-rewrap my lines. I turned it off for Markdown but it's still auto-rewrapping my PR comments.

[Rewrap]: https://github.com/stkb/Rewrap

**Comment by anoadragon453** [comment]
Is there an upstream bug filed that we can follow along with?

**Comment by alexr00** [comment]
Should be fixed here: https://github.com/microsoft/vscode/commit/3f5476f3e699b07648ca79604c4946549d493f93

**Comment by danielo515** [comment]
This issue is still happening folks, never stopped happening to me
